version: "3"
services: 
  app: 
    container_name: docker-node
    restart: always
    build: .
    ports:
      - '3000:3000'
    links: 
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'